#!/bin/bash

# tdrop
# Maintainer:	kyoh86
# License:		MIT License(http://www.opensource.org/licenses/MIT)

for file; do
  if [ "${file:0:1}" != "/" ]; then
    file="${PWD%/}/${file}"
  fi

  echo -e "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${VIM_EDITERM_OPENER}\", \"\", \"$file\"]]\007"
done
