#!/bin/sh

# tdrop
# Maintainer:	kyoh86
# License:		MIT License(http://www.opensource.org/licenses/MIT)

echo "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${VIM_EDITERM_OPENER}\", \"\", \"$1\"]]\007"
