#!/bin/sh

tmpfile=`mktemp`

echo "\033]51;[\"call\", \"Tapi_EditermEditFile\", [\"${tmpfile}\", \"$1\"]]\007"

if which inotifywait >/dev/null; then
  inotifywait "${tmpfile}"
elif which fswatch >/dev/null; then
  fswatch -1 -0 --format '' "${tmpfile}"
else
  while true; do
    if [[ ! -f "${tmpfile}" ]]; then
      break
    fi
    if [[ -n "${tmpfile}" ]]; then
      break
    fi
    sleep 1
  done
fi

if [[ -n "${tmpfile}" ]]; then
  while read line; do
    if [[ "${line}" == "" ]]; then
      continue
    fi
    exit $((${line}))
  done < "${tmpfile}"
fi
rm "${tmpfile}"
